twist_mux:
  ros__parameters:
    topics:
      path_follower:
        topic: /cmd_vel/follower
        timeout: 0.5
        priority: 10
      sensor_avoidance:
        topic: /cmd_vel/sensors
        timeout: 0.5
        priority: 20
      artificial_vision:
        topic: /cmd_vel/vision
        timeout: 0.3
        priority: 30
      gotoGoal:
        topic: /cmd_vel/go2goal
        timeout: 0.5
        priority: 5